# -*- coding: utf-8 -*-
"""Sylvester kwesi Gyamenah - Quiz 1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fp_VyA9sy8OkP3ULpyOBsktmzpy3Lwsq

1.   Import all required libraries
2.   Read in your data, **NB**: The path to the data is **'/content/'**
3.   Select the year from 2005 to 2020 and the boundaries of Ghana.
4.   Calculate the yearly climatology of the data. **NB** Choose the  appropriate statistics  for the variable of interest.
5.   Identify the year with the highest average temperature.
6.   Identify the year with the lowest temperature
7.   Plot the yearly climatologies individually from 2005 to 2020.
**hint** Make use of col_wrap.
"""

import pandas as pd
import xarray as xr
import numpy as np
import matplotlib.pyplot as plt


M = xr.open_dataset('/content/SOIL_MOISTURE.nc')

layer2 = M['stl2']
SM = layer2.sel(time=slice('2005','2020'))
SM

gnlayer2 = SM.groupby('time.year').mean()

gnlayer2.plot.contourf(x = 'latitude', y = 'longitude', col='year',col_wrap=4)













